In [1]:
import tensorflow as tf
import numpy as np

from tensorflow.keras import Model, layers, Input, optimizers, Repet

In [2]:
gpus = tf.config.experimental.list_physical_devices('GPU')
try:
    for gpu in gpus:
        print(gpu)
        tf.config.experimental.set_memory_growth(gpu, True)
except RuntimeError as e:
    print(e)

In [6]:
n_values = 78
n_a = 64
Ty = 100

In [25]:
def one_hot(x):
    x = tf.argmax(x, axis=-1)
    x = tf.one_hot(x, 78) 
    x = tf.keras.layers.RepeatVector(1)(x)
    return x

In [26]:
x = tf.zeros((1, 78))
one_hot(x)

<tf.Tensor: shape=(1, 1, 78), dtype=float32, numpy=
array([[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],
      dtype=float32)>

In [27]:
x0 = Input(shape=(1, n_values))
a0 = Input(shape=(n_a,))
c0 = Input(shape=(n_a,))
outputs = []
a = a0
c = c0
x = x0
lstm = tf.keras.layers.LSTM(n_a, return_state=True)
densor = tf.keras.layers.Dense(n_values, activation='softmax')

for t in range(Ty):
    out, a, c = lstm(x, initial_state=(a, c))
    out = densor(out)
    outputs.append(out)
    x =  tf.keras.layers.Lambda(one_hot)(out) 
inference_model = tf.keras.Model(inputs=[x0, a0, c0], outputs=outputs)

In [9]:
inference_model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_4 (InputLayer)            [(None, 1, 78)]      0                                            
__________________________________________________________________________________________________
input_5 (InputLayer)            [(None, 64)]         0                                            
__________________________________________________________________________________________________
input_6 (InputLayer)            [(None, 64)]         0                                            
__________________________________________________________________________________________________
lstm_1 (LSTM)                   multiple             36608       input_4[0][0]                    
                                                                 input_5[0][0]                

In [28]:
inference_model.inputs

[<tf.Tensor 'input_10:0' shape=(None, 1, 78) dtype=float32>,
 <tf.Tensor 'input_11:0' shape=(None, 64) dtype=float32>,
 <tf.Tensor 'input_12:0' shape=(None, 64) dtype=float32>]

In [29]:
inference_model.outputs


[<tf.Tensor 'dense_3/Identity:0' shape=(None, 78) dtype=float32>,
 <tf.Tensor 'dense_3_1/Identity:0' shape=(None, 78) dtype=float32>,
 <tf.Tensor 'dense_3_2/Identity:0' shape=(None, 78) dtype=float32>,
 <tf.Tensor 'dense_3_3/Identity:0' shape=(None, 78) dtype=float32>,
 <tf.Tensor 'dense_3_4/Identity:0' shape=(None, 78) dtype=float32>,
 <tf.Tensor 'dense_3_5/Identity:0' shape=(None, 78) dtype=float32>,
 <tf.Tensor 'dense_3_6/Identity:0' shape=(None, 78) dtype=float32>,
 <tf.Tensor 'dense_3_7/Identity:0' shape=(None, 78) dtype=float32>,
 <tf.Tensor 'dense_3_8/Identity:0' shape=(None, 78) dtype=float32>,
 <tf.Tensor 'dense_3_9/Identity:0' shape=(None, 78) dtype=float32>,
 <tf.Tensor 'dense_3_10/Identity:0' shape=(None, 78) dtype=float32>,
 <tf.Tensor 'dense_3_11/Identity:0' shape=(None, 78) dtype=float32>,
 <tf.Tensor 'dense_3_12/Identity:0' shape=(None, 78) dtype=float32>,
 <tf.Tensor 'dense_3_13/Identity:0' shape=(None, 78) dtype=float32>,
 <tf.Tensor 'dense_3_14/Identity:0' shape=(Non

In [30]:
x_ = tf.zeros((1, 1, 78))
a_ = tf.zeros((1, n_a))
c_ = tf.zeros((1, n_a))
inference_model([x_, a_, c_])

[<tf.Tensor: shape=(1, 78), dtype=float32, numpy=
 array([[0.01282051, 0.01282051, 0.01282051, 0.01282051, 0.01282051,
         0.01282051, 0.01282051, 0.01282051, 0.01282051, 0.01282051,
         0.01282051, 0.01282051, 0.01282051, 0.01282051, 0.01282051,
         0.01282051, 0.01282051, 0.01282051, 0.01282051, 0.01282051,
         0.01282051, 0.01282051, 0.01282051, 0.01282051, 0.01282051,
         0.01282051, 0.01282051, 0.01282051, 0.01282051, 0.01282051,
         0.01282051, 0.01282051, 0.01282051, 0.01282051, 0.01282051,
         0.01282051, 0.01282051, 0.01282051, 0.01282051, 0.01282051,
         0.01282051, 0.01282051, 0.01282051, 0.01282051, 0.01282051,
         0.01282051, 0.01282051, 0.01282051, 0.01282051, 0.01282051,
         0.01282051, 0.01282051, 0.01282051, 0.01282051, 0.01282051,
         0.01282051, 0.01282051, 0.01282051, 0.01282051, 0.01282051,
         0.01282051, 0.01282051, 0.01282051, 0.01282051, 0.01282051,
         0.01282051, 0.01282051, 0.01282051, 0.012820